### ISSUE TITLE
Letters are rotated 90 degrees clockwise

### ISSUE THREAD

**Issue by max-nova** [bostonpythonworkshop/ColorWall#4]
When running:

python run.py LetterTest

the letters are rotated 90 degrees clockwise

![rotated](https://f.cloud.github.com/assets/960231/121164/af18b31a-6d78-11e2-9674-296373722f9c.png)

**Comment by jroth84** [comment]
Here's a patch that fixes it:
diff --git a/ascii8x8.py b/ascii8x8.py
index 74816cf..ca5c36c 100644
--- a/ascii8x8.py
+++ b/ascii8x8.py
@@ -16,9 +16,9 @@ def draw_chr(ch, wall, foreground, background, x_offset=0, y_off
     for y, row in enumerate(font):
         for x, col in enumerate(row):
             if col == '#':
-                wall.set_pixel(y + y_offset, x + x_offset, background)
-                wall.set_pixel(x + x_offset, y + y_offset, background)
           else:
-                wall.set_pixel(y + y_offset, x + x_offset, foreground)
- ```
             wall.set_pixel(x + x_offset, y + y_offset, foreground)
  ```
  
  Font8x8 = (
   (
